### ISSUE TITLE
next (any) release to-do list

### ISSUE THREAD

**Issue by jcxldn** [SolteraGG/StickyAPI#82]
- [x] Update since references to TBA in `StickyAPI.java` (from #77)
- [x] Add since references to #92. (especially StringUtil changes) 

- [x]  (optional) Add since references to #72.
